### ISSUE TITLE
Packing Behaviour

### ISSUE THREAD

**Issue by lassade** [chinedufn/rectangle-pack#5]
Hi! while trying to pack a bunch of glyphs inside a rectangle I notice this strange behaviour where my atlas will start be filled in the diagonal, from the top left to the bottom right and then branching to the sides, is that the right behaviour?

I also reach a point where the packing whould give an not enough space error, but visually having quite a bit of space to spare. For instance in the next example I can't pack everything together into a single atlas. What is happening?

<details>
  <summary>Rectangle Pack Results (warning! very white images)</summary>

![Ubuntu-L-00](https://user-images.githubusercontent.com/9643105/182724811-0d6477ad-3357-4919-bac4-297f366a7ea9.png)
![Ubuntu-L-01](https://user-images.githubusercontent.com/9643105/182724815-984e051c-70e6-4615-bc9f-d5fe8bd84553.png)

</details>

In contrast using a skyline heuristic (from `texture_packer`) I got mutch better results, using the same settings

<details>
  <summary>Skyline Results</summary>

![Ubuntu-L](https://user-images.githubusercontent.com/9643105/182728615-bd8ca8ce-4739-4300-8c33-46fdb2429924.png)

</details>

**Comment by lassade** [comment]
Ok I think I know what is happening.

Since the current implementation doesn't handle rotation it gives the impression of filling along the diagonal first but the packer just doesn't do that.

The packer is working as intended, is just it can't deal with an unsorted input very well in this particular case, the `rectpack2D` uses a function that tries different input sortings to maximize the packing efficiency.

There is some weird input data out there...

**Comment by chinedufn** [comment]
Thanks for looking into this!

> Since the current implementation doesn't handle rotation it gives the impression of filling along the diagonal first but the packer just doesn't do that.

I'd be happy to review a PR that adds rotation support. If you only need 2D rotation then we would just need Z-axis rotation support.

> the rectpack2D uses a function that tries different input sortings to maximize the packing efficiency.

`rectangle-pack` intentionally gives the user control of the heuristics used when packing.

We take in two functions that allow you to control how things are placed.

If you want to try multiple algorithms, you can just run multiple pack multiple times with different passed in heuristic functions.

https://github.com/chinedufn/rectangle-pack/blob/de824b1f6c4171ce37e3f2dce2f22d881d595343/src/lib.rs#L139-L140

To match `rectpack2d` you would run `rectangle-pack` six times so that you could compare using the 6 different algorithms that `rectpack2d` uses (the user would need to provide the algorithm themself. I would also be open to a PR that exposes common heuristics)

https://github.com/chinedufn/rectangle-pack/blob/99774a40a2cba9d380614ad87b463a981c6b1cee/src/box_size_heuristics.rs#L10-L13

https://github.com/chinedufn/rectangle-pack/blob/de824b1f6c4171ce37e3f2dce2f22d881d595343/src/bin_section.rs#L27-L42

---

After you ran it six times you would need to compare the 6 to see which was packed the tightest.

This part isn't possible yet, but I'd be happy to review a PR that implements it.

https://github.com/chinedufn/rectangle-pack#stats-on-how-the-bins-were-packed

<img width="883" alt="image" src="https://user-images.githubusercontent.com/2099811/183088653-ba6ae136-6555-4c29-829e-231ac737fdcb.png">

---

Thanks for opening this issue! Let me know if you're interested in any of the above and I'd be happy to provide any guidance needed on how to implement it.

Cheers!

**Comment by lassade** [comment]
hi chinedufn! Thanks for writing this crate, but I'm going in another direction.
